/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import actores.*;

/**
 * Esta va a ser la ventana en la que se enlace la logica de manejo de datos y 
 * el resultado en pantalla que debe obtener el usuario que interactue con el 
 * software
 * @author Jhonnier Hernandez
 */
public class VentanaGestion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaGestion
     */
    public VentanaGestion() {
        initComponents();
        gestionAfiliados = new GestionAfiliados();
        gestionMedicos = new GestionMedicos();
        gestionConsultorios = new GestionConsultorios();
        gestionServicios = new GestionServiciosMedicos();
        jTextArea1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblGestionar = new javax.swing.JLabel();
        jComboBoxOpciones = new javax.swing.JComboBox<>();
        btnOk = new javax.swing.JButton();
        jComboBoxOpciones1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        lblGestionar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGestionar.setText("GESTIONAR: ");

        jComboBoxOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AFILIADOS", "MEDICOS", "CONSULTORIOS", "SERVICIOS", "CITAS" }));

        btnOk.setText("OK");
        btnOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOkMouseClicked(evt);
            }
        });

        jComboBoxOpciones1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AGREGAR", "LISTAR", "ACTUALIZAR", "ELIMINAR", "CSV", " " }));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGestionar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxOpciones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGestionar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOk)
                            .addComponent(jComboBoxOpciones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMouseClicked
        // TODO add your handling code here:
        accionEjecutada();
        ejecutarAccion(opcion1, opcion2);
    }//GEN-LAST:event_btnOkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaGestion().setVisible(true);
            }
        });
    }
    
    private void ejecutarAccion(int opcion1, int opcion2){
     
        switch(opcion1){
            case 0 -> {
                switch(opcion2){
                    case 0 -> gestionAfiliados.agregar();
                    case 1 -> jTextArea1.setText(gestionAfiliados.listar());
                    case 2 -> gestionAfiliados.actualizar();
                    case 3 -> gestionAfiliados.eliminar();
                    case 4 -> gestionAfiliados.generarCSV();
                }
            }
            
            case 1 -> {
                switch(opcion2){
                    case 0 -> gestionMedicos.agregar();
                    case 1 -> jTextArea1.setText(gestionMedicos.listar());
                    case 2 -> gestionMedicos.actualizar();
                    case 3 -> gestionMedicos.eliminar();
                    case 4 -> gestionMedicos.generarCSV();
                }
            }
                
            case 2 -> {
                switch(opcion2){
                    case 0 -> gestionConsultorios.agregar();
                    case 1 -> jTextArea1.setText(gestionConsultorios.listar());
                    case 2 -> gestionConsultorios.actualizar();
                    case 3 -> gestionConsultorios.eliminar();
                    case 4 -> gestionConsultorios.generarCSV();
                }
            }
                
            case 3 -> {
                switch(opcion2){
                    case 0 -> gestionServicios.agregar();
                    case 1 -> jTextArea1.setText(gestionServicios.listar());
                    case 2 -> gestionServicios.actualizar();
                    case 3 -> gestionServicios.eliminar();
                    case 4 -> gestionServicios.generarCSV();
                }
            }
            
            case 4 -> {
                switch(opcion2){
                    case 0 -> jTextArea1.setText("agregar cita medica");
                    case 1 -> jTextArea1.setText("listar citas medicas");
                    case 2 -> jTextArea1.setText("actualizar cita medica");
                    case 3 -> jTextArea1.setText("eliminar cita medica");
                    case 4 -> jTextArea1.setText("crear SVC citas medicas");
                }
            }
        }
    }
    private void accionEjecutada(){
        //jTextArea1.setEnabled(false);
        opcion1 = jComboBoxOpciones.getSelectedIndex();
        opcion2 = jComboBoxOpciones1.getSelectedIndex();
        
        switch(jComboBoxOpciones.getSelectedIndex()){
            case 0 -> {
                switch(jComboBoxOpciones1.getSelectedIndex()){
                    case 0 -> jTextArea1.setText("agregar afiliado");
                    case 1 -> jTextArea1.setText("listar afiliados");
                    case 2 -> jTextArea1.setText("actualizar afiliado");
                    case 3 -> jTextArea1.setText("eliminar afiliado");
                    case 4 -> jTextArea1.setText("crear SVC afiliados");
                }
            }
                
            case 1 -> {
                switch(jComboBoxOpciones1.getSelectedIndex()){
                    case 0 -> jTextArea1.setText("agregar medico");
                    case 1 -> jTextArea1.setText("listar medicos");
                    case 2 -> jTextArea1.setText("actualizar medico");
                    case 3 -> jTextArea1.setText("eliminar medico");
                    case 4 -> jTextArea1.setText("crear SVC medicos");
                }
            }
                
            case 2 -> {
                switch(jComboBoxOpciones1.getSelectedIndex()){
                    case 0 -> jTextArea1.setText("agregar consultorio");
                    case 1 -> jTextArea1.setText("listar consultorios");
                    case 2 -> jTextArea1.setText("actualizar consultorio");
                    case 3 -> jTextArea1.setText("eliminar consultorio");
                    case 4 -> jTextArea1.setText("crear SVC consultorios");
                }
            }
                
            case 3 -> {
                switch(jComboBoxOpciones1.getSelectedIndex()){
                    case 0 -> jTextArea1.setText("agregar servicio medico");
                    case 1 -> jTextArea1.setText("listar servicios medicos");
                    case 2 -> jTextArea1.setText("actualizar servicio medico");
                    case 3 -> jTextArea1.setText("eliminar servicio medico");
                    case 4 -> jTextArea1.setText("crear SVC servicios medicos");
                }
            }
            
            case 4 -> {
                switch(jComboBoxOpciones1.getSelectedIndex()){
                    case 0 -> jTextArea1.setText("agregar cita medica");
                    case 1 -> jTextArea1.setText("listar citas medicas");
                    case 2 -> jTextArea1.setText("actualizar cita medica");
                    case 3 -> jTextArea1.setText("eliminar cita medica");
                    case 4 -> jTextArea1.setText("crear SVC citas medicas");
                }
            }
        }
    }
    
    
    private GestionServiciosMedicos gestionServicios;
    private GestionConsultorios gestionConsultorios;
    private GestionMedicos gestionMedicos;
    private GestionAfiliados gestionAfiliados;
    private int opcion1;
    private int opcion2;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<String> jComboBoxOpciones;
    private javax.swing.JComboBox<String> jComboBoxOpciones1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblGestionar;
    // End of variables declaration//GEN-END:variables
}
